### ISSUE TITLE
Rewrite in rust(🚀)?

### ISSUE THREAD

**Issue by simon511000** [ThibaultMINNEBOO/bot_base#1]
your bot in rust(🚀) could benefit from:
- zero🚀cost 🚀 abstractions 🚀
- move 🚀 semantics 
- guaranteed 🚀 memory 🚀 safety 
- threads 🚀 without 🚀 data 🚀 races
- trait🚀based 🚀 generics 🚀
- pattern 🚀 matching 🚀
- type 🚀 inference 🚀
- minimal 🚀 runtime 🚀
- efficient 🚀 C(ringe) 🚀 bindings 🚀

**Comment by ThibaultMINNEBOO** [comment]
J'y réfléchirai soigneusement, merci pour ton avis

**Comment by simon511000** [comment]
up ?
